name: Terragrunt PR Review

on:
  pull_request:
    paths:
      - "**.hcl"
      - "**.tf"
      - ".github/workflows/terragrunt.yml"

permissions:
  contents: read
  pull-requests: write
  id-token: write # For OIDC authentication

env:
  TF_LOG: INFO
  AWS_REGION: us-east-1

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
      has-changes: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tf
            **/*.hcl
            **/*.json
            **/*.yaml
            **/*.yml
          separator: ","

  terragrunt-plan:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole-${{ matrix.environment }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            **/.terraform/providers
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Run Terragrunt Plan
        uses: boogy/terragrunt-runner@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-detect: true
          changed-files: ${{ needs.detect-changes.outputs.changed-files }}
          file-patterns: "*.hcl,*.json,*.yaml,*.yml"
          terragrunt-file: terragrunt.hcl
          max-walk-up: 5
          command: "run --all -- plan"
          terragrunt-args: |
            --non-interactive
            --tf-forward-stdout
            --queue-include-external
          delete-old-comments: true

  terragrunt-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate all Terragrunt configurations
        uses: boogy/terragrunt-runner@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folders: |
            modules
            environments
          command: "run --all validate"
          terragrunt-args: --non-interactive
          parallel: true

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Terragrunt formatting
        run: |
          terragrunt hcl fmt --check --diff
        continue-on-error: true

      - name: Check Terraform formatting
        run: |
          terraform hcl fmt --check -recursive
        continue-on-error: true
