name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build Binary
        run: |
          BINARY_NAME="terragrunt-runner-${{ matrix.goos }}-${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -o $BINARY_NAME -ldflags "-X main.Version=${GITHUB_REF#refs/tags/} -X main.Commit=$(git rev-parse --short HEAD) -X main.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt-runner-${{ matrix.goos }}-${{ matrix.goarch }}
          path: terragrunt-runner-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: terragrunt-runner-*
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
        with:
          files: binaries/**/*
          tag_name: ${{ github.ref_name }}
          overwrite_files: false # Disable overwrite to avoid 404 on non-existent assets
